#pragma once

namespace OBJECT
{
	enum TYPE 
	{ 
		SPACE, SPACEITEM, MAP, UIBACK, MOVETILE, LIGHT, PORTAL, ITEM, 
		JUNGLE_MINION_NEAR, JUNGLE_MINION_DIST,
		BLUE_TOWER, RED_TOWER, 
		BLUE_MINION_NEAR, RED_MINION_NEAR, 
		BLUE_MINION_DIST, RED_MINION_DIST, 
		BLUE_HERO, RED_HERO, 
		PLAYER, 
		BLUE_ELEMENT, RED_ELEMENT, 
		SPACEENDING, BOOSTER, INCUBATOR,
		UNITFRONT, HURT, UI, MYTABLE, MOUSE, TYPE_END
	};
}

enum TILE_TYPE
{
	COLL_ALL, COLL_UP, COLL_JUMP, RED_STOP, RED_JUMP, BLUE_STOP, BLUE_JUMP
};

enum TEAM_TYPE
{
	RED, BLUE, JUNGLE, TEAM_TYPE_END
};

enum UNIT_TYPE
{
	HERO, MINION, UNIT_TYPE_END
};

enum MINION_AI_TYPE
{
	UP, DOWN, M_AI_TYPE_END
};

enum DIR
{
	LEFT, RIGHT, DIR_END
};

enum SKILL_TYPE
{
	ONE, TWO, THREE, FOUR, TAXI, COOLTIME, SKILL_END
};